project:
  type: website

website:
  title: "cnecon"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cnecon97
      - icon: twitter
        href: https://twitter.com/econcn
format:
  html:
    theme: cosmo
    css: styles.css



