project:
  type: website
  output-dir: docs

website:
  title: "cnecon"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cnecon97/cnecon
      - icon: twitter
        href: https://twitter.com/econcn
format:
  html:
    theme: cosmo
    css: styles.css

comments:
  giscus: 
    repo: cnecon97/cnecon

